# Generated by Django 4.2.6 on 2024-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
