# Generated by Django 4.2.6 on 2024-04-25 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0004_placedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='side',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
