# Generated by Django 4.2.6 on 2024-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0006_remove_placedorder_side_placedorder_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='orderid',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
